#define HAVE_PROPER_ICONV 1

#define __CLEANUP_C 1
#define PTW32_BUILD_INLINED 1
#define PTW32_STATIC_LIB 1
#define HAVE_PTW32_CONFIG_H 1

#define PIC 1

#define STDC_HEADERS 1
#define WORDS_LITTLEENDIAN 1
#define CORO_LOSER 1
#define _FILE_OFFSET_BITS 64
#define EMBED_LIBEIO 1

#ifndef _GNU_SOURCE
#define _GNU_SOURCE 1
#endif


#define EV_STANDALONE 1

#define HAVE_INTTYPES_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRINGS_H 1
#define HAVE_STRING_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_UNISTD_H 1

#define HAVE_FLOOR 1

#define EV_STAT_ENABLE 0
